before:
  hooks:
  - go mod tidy
  # - go generate ./...
builds:
- main: ./cmd/gofish
  flags:
  - -trimpath
  tags:
  - osusergo
  - netgo
  - static_build
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s
  - -w
  - -X github.com/piccobit/gofish/version.version={{.Version}}
  - -X github.com/piccobit/gofish/version.commit={{.Commit}}
  - -X github.com/piccobit/gofish/version.date={{.CommitDate}}
  - -X github.com/piccobit/gofish/version.buildBy=HDS
  mod_timestamp: "{{ .CommitTimestamp }}"
archives:
- name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE*
  - README*
  - CHANGELOG*
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
