name: test
on: pull_request
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: build
      run: make
    - name: run style tests
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.49
        args: --tests --disable-all --enable=gofmt --enable=misspell --enable=deadcode --enable=ineffassign --enable=govet
    - name: run unit tests
      run: go test ./...
